// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

/**
 * <pre>
 * Command extends base message
 * </pre>
 *
 * Protobuf type {@code broker.BrokeredBaseCommand}
 */
public final class BrokeredBaseCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.BrokeredBaseCommand)
    BrokeredBaseCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokeredBaseCommand.newBuilder() to construct.
  private BrokeredBaseCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokeredBaseCommand() {
    tcSessionId_ = "";
    eventHubPartitionIds_ = "";
    currentContextSessionId_ = "";
    currentContextActionId_ = "";
    locale_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokeredBaseCommand();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.BrokeredBaseCommand.class, com.example.grpc.BrokeredBaseCommand.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_FIELD_NUMBER = 1;
  private com.example.grpc.BrokeredBaseMessage base_;
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return Whether the base field is set.
   */
  @java.lang.Override
  public boolean hasBase() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return The base.
   */
  @java.lang.Override
  public com.example.grpc.BrokeredBaseMessage getBase() {
    return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
  }
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   */
  @java.lang.Override
  public com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder() {
    return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
  }

  public static final int TCSESSIONID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tcSessionId_ = "";
  /**
   * <code>string tcSessionId = 2;</code>
   * @return The tcSessionId.
   */
  @java.lang.Override
  public java.lang.String getTcSessionId() {
    java.lang.Object ref = tcSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tcSessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string tcSessionId = 2;</code>
   * @return The bytes for tcSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTcSessionIdBytes() {
    java.lang.Object ref = tcSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tcSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTHUBPARTITIONIDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventHubPartitionIds_ = "";
  /**
   * <code>string eventHubPartitionIds = 3;</code>
   * @return The eventHubPartitionIds.
   */
  @java.lang.Override
  public java.lang.String getEventHubPartitionIds() {
    java.lang.Object ref = eventHubPartitionIds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventHubPartitionIds_ = s;
      return s;
    }
  }
  /**
   * <code>string eventHubPartitionIds = 3;</code>
   * @return The bytes for eventHubPartitionIds.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventHubPartitionIdsBytes() {
    java.lang.Object ref = eventHubPartitionIds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventHubPartitionIds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTCONTEXTSESSIONID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currentContextSessionId_ = "";
  /**
   * <code>string currentContextSessionId = 4;</code>
   * @return The currentContextSessionId.
   */
  @java.lang.Override
  public java.lang.String getCurrentContextSessionId() {
    java.lang.Object ref = currentContextSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentContextSessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string currentContextSessionId = 4;</code>
   * @return The bytes for currentContextSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentContextSessionIdBytes() {
    java.lang.Object ref = currentContextSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentContextSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTCONTEXTACTIONID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currentContextActionId_ = "";
  /**
   * <code>string currentContextActionId = 5;</code>
   * @return The currentContextActionId.
   */
  @java.lang.Override
  public java.lang.String getCurrentContextActionId() {
    java.lang.Object ref = currentContextActionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentContextActionId_ = s;
      return s;
    }
  }
  /**
   * <code>string currentContextActionId = 5;</code>
   * @return The bytes for currentContextActionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentContextActionIdBytes() {
    java.lang.Object ref = currentContextActionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentContextActionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object locale_ = "";
  /**
   * <code>string locale = 6;</code>
   * @return The locale.
   */
  @java.lang.Override
  public java.lang.String getLocale() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locale_ = s;
      return s;
    }
  }
  /**
   * <code>string locale = 6;</code>
   * @return The bytes for locale.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBase());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcSessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tcSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventHubPartitionIds_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventHubPartitionIds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentContextSessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currentContextSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentContextActionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, currentContextActionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locale_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, locale_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBase());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcSessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tcSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventHubPartitionIds_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventHubPartitionIds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentContextSessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currentContextSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentContextActionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, currentContextActionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locale_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, locale_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.BrokeredBaseCommand)) {
      return super.equals(obj);
    }
    com.example.grpc.BrokeredBaseCommand other = (com.example.grpc.BrokeredBaseCommand) obj;

    if (hasBase() != other.hasBase()) return false;
    if (hasBase()) {
      if (!getBase()
          .equals(other.getBase())) return false;
    }
    if (!getTcSessionId()
        .equals(other.getTcSessionId())) return false;
    if (!getEventHubPartitionIds()
        .equals(other.getEventHubPartitionIds())) return false;
    if (!getCurrentContextSessionId()
        .equals(other.getCurrentContextSessionId())) return false;
    if (!getCurrentContextActionId()
        .equals(other.getCurrentContextActionId())) return false;
    if (!getLocale()
        .equals(other.getLocale())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBase()) {
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
    }
    hash = (37 * hash) + TCSESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getTcSessionId().hashCode();
    hash = (37 * hash) + EVENTHUBPARTITIONIDS_FIELD_NUMBER;
    hash = (53 * hash) + getEventHubPartitionIds().hashCode();
    hash = (37 * hash) + CURRENTCONTEXTSESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentContextSessionId().hashCode();
    hash = (37 * hash) + CURRENTCONTEXTACTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentContextActionId().hashCode();
    hash = (37 * hash) + LOCALE_FIELD_NUMBER;
    hash = (53 * hash) + getLocale().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.BrokeredBaseCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.BrokeredBaseCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredBaseCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.BrokeredBaseCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Command extends base message
   * </pre>
   *
   * Protobuf type {@code broker.BrokeredBaseCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.BrokeredBaseCommand)
      com.example.grpc.BrokeredBaseCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.BrokeredBaseCommand.class, com.example.grpc.BrokeredBaseCommand.Builder.class);
    }

    // Construct using com.example.grpc.BrokeredBaseCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBaseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      tcSessionId_ = "";
      eventHubPartitionIds_ = "";
      currentContextSessionId_ = "";
      currentContextActionId_ = "";
      locale_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseCommand_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseCommand getDefaultInstanceForType() {
      return com.example.grpc.BrokeredBaseCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseCommand build() {
      com.example.grpc.BrokeredBaseCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseCommand buildPartial() {
      com.example.grpc.BrokeredBaseCommand result = new com.example.grpc.BrokeredBaseCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.BrokeredBaseCommand result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = baseBuilder_ == null
            ? base_
            : baseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tcSessionId_ = tcSessionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.eventHubPartitionIds_ = eventHubPartitionIds_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.currentContextSessionId_ = currentContextSessionId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.currentContextActionId_ = currentContextActionId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.locale_ = locale_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.BrokeredBaseCommand) {
        return mergeFrom((com.example.grpc.BrokeredBaseCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.BrokeredBaseCommand other) {
      if (other == com.example.grpc.BrokeredBaseCommand.getDefaultInstance()) return this;
      if (other.hasBase()) {
        mergeBase(other.getBase());
      }
      if (!other.getTcSessionId().isEmpty()) {
        tcSessionId_ = other.tcSessionId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEventHubPartitionIds().isEmpty()) {
        eventHubPartitionIds_ = other.eventHubPartitionIds_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getCurrentContextSessionId().isEmpty()) {
        currentContextSessionId_ = other.currentContextSessionId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getCurrentContextActionId().isEmpty()) {
        currentContextActionId_ = other.currentContextActionId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLocale().isEmpty()) {
        locale_ = other.locale_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tcSessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              eventHubPartitionIds_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              currentContextSessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              currentContextActionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              locale_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.example.grpc.BrokeredBaseMessage base_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder> baseBuilder_;
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     * @return Whether the base field is set.
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     * @return The base.
     */
    public com.example.grpc.BrokeredBaseMessage getBase() {
      if (baseBuilder_ == null) {
        return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
      } else {
        return baseBuilder_.getMessage();
      }
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder setBase(com.example.grpc.BrokeredBaseMessage value) {
      if (baseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        base_ = value;
      } else {
        baseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder setBase(
        com.example.grpc.BrokeredBaseMessage.Builder builderForValue) {
      if (baseBuilder_ == null) {
        base_ = builderForValue.build();
      } else {
        baseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder mergeBase(com.example.grpc.BrokeredBaseMessage value) {
      if (baseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          base_ != null &&
          base_ != com.example.grpc.BrokeredBaseMessage.getDefaultInstance()) {
          getBaseBuilder().mergeFrom(value);
        } else {
          base_ = value;
        }
      } else {
        baseBuilder_.mergeFrom(value);
      }
      if (base_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder clearBase() {
      bitField0_ = (bitField0_ & ~0x00000001);
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public com.example.grpc.BrokeredBaseMessage.Builder getBaseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder() {
      if (baseBuilder_ != null) {
        return baseBuilder_.getMessageOrBuilder();
      } else {
        return base_ == null ?
            com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
      }
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder> 
        getBaseFieldBuilder() {
      if (baseBuilder_ == null) {
        baseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder>(
                getBase(),
                getParentForChildren(),
                isClean());
        base_ = null;
      }
      return baseBuilder_;
    }

    private java.lang.Object tcSessionId_ = "";
    /**
     * <code>string tcSessionId = 2;</code>
     * @return The tcSessionId.
     */
    public java.lang.String getTcSessionId() {
      java.lang.Object ref = tcSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tcSessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tcSessionId = 2;</code>
     * @return The bytes for tcSessionId.
     */
    public com.google.protobuf.ByteString
        getTcSessionIdBytes() {
      java.lang.Object ref = tcSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tcSessionId = 2;</code>
     * @param value The tcSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setTcSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tcSessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tcSessionId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTcSessionId() {
      tcSessionId_ = getDefaultInstance().getTcSessionId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tcSessionId = 2;</code>
     * @param value The bytes for tcSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setTcSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tcSessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object eventHubPartitionIds_ = "";
    /**
     * <code>string eventHubPartitionIds = 3;</code>
     * @return The eventHubPartitionIds.
     */
    public java.lang.String getEventHubPartitionIds() {
      java.lang.Object ref = eventHubPartitionIds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventHubPartitionIds_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventHubPartitionIds = 3;</code>
     * @return The bytes for eventHubPartitionIds.
     */
    public com.google.protobuf.ByteString
        getEventHubPartitionIdsBytes() {
      java.lang.Object ref = eventHubPartitionIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventHubPartitionIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventHubPartitionIds = 3;</code>
     * @param value The eventHubPartitionIds to set.
     * @return This builder for chaining.
     */
    public Builder setEventHubPartitionIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventHubPartitionIds_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string eventHubPartitionIds = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventHubPartitionIds() {
      eventHubPartitionIds_ = getDefaultInstance().getEventHubPartitionIds();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string eventHubPartitionIds = 3;</code>
     * @param value The bytes for eventHubPartitionIds to set.
     * @return This builder for chaining.
     */
    public Builder setEventHubPartitionIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventHubPartitionIds_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object currentContextSessionId_ = "";
    /**
     * <code>string currentContextSessionId = 4;</code>
     * @return The currentContextSessionId.
     */
    public java.lang.String getCurrentContextSessionId() {
      java.lang.Object ref = currentContextSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentContextSessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentContextSessionId = 4;</code>
     * @return The bytes for currentContextSessionId.
     */
    public com.google.protobuf.ByteString
        getCurrentContextSessionIdBytes() {
      java.lang.Object ref = currentContextSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentContextSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentContextSessionId = 4;</code>
     * @param value The currentContextSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentContextSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currentContextSessionId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string currentContextSessionId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentContextSessionId() {
      currentContextSessionId_ = getDefaultInstance().getCurrentContextSessionId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string currentContextSessionId = 4;</code>
     * @param value The bytes for currentContextSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentContextSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currentContextSessionId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object currentContextActionId_ = "";
    /**
     * <code>string currentContextActionId = 5;</code>
     * @return The currentContextActionId.
     */
    public java.lang.String getCurrentContextActionId() {
      java.lang.Object ref = currentContextActionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentContextActionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentContextActionId = 5;</code>
     * @return The bytes for currentContextActionId.
     */
    public com.google.protobuf.ByteString
        getCurrentContextActionIdBytes() {
      java.lang.Object ref = currentContextActionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentContextActionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentContextActionId = 5;</code>
     * @param value The currentContextActionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentContextActionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currentContextActionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string currentContextActionId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentContextActionId() {
      currentContextActionId_ = getDefaultInstance().getCurrentContextActionId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string currentContextActionId = 5;</code>
     * @param value The bytes for currentContextActionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentContextActionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currentContextActionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object locale_ = "";
    /**
     * <code>string locale = 6;</code>
     * @return The locale.
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string locale = 6;</code>
     * @return The bytes for locale.
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string locale = 6;</code>
     * @param value The locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocale(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      locale_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string locale = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocale() {
      locale_ = getDefaultInstance().getLocale();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string locale = 6;</code>
     * @param value The bytes for locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      locale_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.BrokeredBaseCommand)
  }

  // @@protoc_insertion_point(class_scope:broker.BrokeredBaseCommand)
  private static final com.example.grpc.BrokeredBaseCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.BrokeredBaseCommand();
  }

  public static com.example.grpc.BrokeredBaseCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokeredBaseCommand>
      PARSER = new com.google.protobuf.AbstractParser<BrokeredBaseCommand>() {
    @java.lang.Override
    public BrokeredBaseCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BrokeredBaseCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokeredBaseCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.BrokeredBaseCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

