// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface BrokeredBaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.BrokeredBaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return The base.
   */
  com.example.grpc.BrokeredBaseMessage getBase();
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   */
  com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder();

  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   * @return Whether the resultStatus field is set.
   */
  boolean hasResultStatus();
  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   * @return The resultStatus.
   */
  com.example.grpc.BrokeredResultStatus getResultStatus();
  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   */
  com.example.grpc.BrokeredResultStatusOrBuilder getResultStatusOrBuilder();

  /**
   * <code>string locale = 3;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 3;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();
}
