// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface BrokeredBaseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.BrokeredBaseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string correlationId = 1;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlationId = 1;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string tcUserId = 3;</code>
   * @return The tcUserId.
   */
  java.lang.String getTcUserId();
  /**
   * <code>string tcUserId = 3;</code>
   * @return The bytes for tcUserId.
   */
  com.google.protobuf.ByteString
      getTcUserIdBytes();

  /**
   * <code>string siteId = 4;</code>
   * @return The siteId.
   */
  java.lang.String getSiteId();
  /**
   * <code>string siteId = 4;</code>
   * @return The bytes for siteId.
   */
  com.google.protobuf.ByteString
      getSiteIdBytes();
}
