// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

/**
 * <pre>
 * Response extends base message
 * </pre>
 *
 * Protobuf type {@code broker.BrokeredBaseResponse}
 */
public final class BrokeredBaseResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.BrokeredBaseResponse)
    BrokeredBaseResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokeredBaseResponse.newBuilder() to construct.
  private BrokeredBaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokeredBaseResponse() {
    locale_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokeredBaseResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.BrokeredBaseResponse.class, com.example.grpc.BrokeredBaseResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_FIELD_NUMBER = 1;
  private com.example.grpc.BrokeredBaseMessage base_;
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return Whether the base field is set.
   */
  @java.lang.Override
  public boolean hasBase() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return The base.
   */
  @java.lang.Override
  public com.example.grpc.BrokeredBaseMessage getBase() {
    return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
  }
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   */
  @java.lang.Override
  public com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder() {
    return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
  }

  public static final int RESULTSTATUS_FIELD_NUMBER = 2;
  private com.example.grpc.BrokeredResultStatus resultStatus_;
  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   * @return Whether the resultStatus field is set.
   */
  @java.lang.Override
  public boolean hasResultStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   * @return The resultStatus.
   */
  @java.lang.Override
  public com.example.grpc.BrokeredResultStatus getResultStatus() {
    return resultStatus_ == null ? com.example.grpc.BrokeredResultStatus.getDefaultInstance() : resultStatus_;
  }
  /**
   * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
   */
  @java.lang.Override
  public com.example.grpc.BrokeredResultStatusOrBuilder getResultStatusOrBuilder() {
    return resultStatus_ == null ? com.example.grpc.BrokeredResultStatus.getDefaultInstance() : resultStatus_;
  }

  public static final int LOCALE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object locale_ = "";
  /**
   * <code>string locale = 3;</code>
   * @return The locale.
   */
  @java.lang.Override
  public java.lang.String getLocale() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locale_ = s;
      return s;
    }
  }
  /**
   * <code>string locale = 3;</code>
   * @return The bytes for locale.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBase());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getResultStatus());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locale_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, locale_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBase());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResultStatus());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locale_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, locale_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.BrokeredBaseResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.BrokeredBaseResponse other = (com.example.grpc.BrokeredBaseResponse) obj;

    if (hasBase() != other.hasBase()) return false;
    if (hasBase()) {
      if (!getBase()
          .equals(other.getBase())) return false;
    }
    if (hasResultStatus() != other.hasResultStatus()) return false;
    if (hasResultStatus()) {
      if (!getResultStatus()
          .equals(other.getResultStatus())) return false;
    }
    if (!getLocale()
        .equals(other.getLocale())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBase()) {
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
    }
    if (hasResultStatus()) {
      hash = (37 * hash) + RESULTSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getResultStatus().hashCode();
    }
    hash = (37 * hash) + LOCALE_FIELD_NUMBER;
    hash = (53 * hash) + getLocale().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.BrokeredBaseResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.BrokeredBaseResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredBaseResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.BrokeredBaseResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response extends base message
   * </pre>
   *
   * Protobuf type {@code broker.BrokeredBaseResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.BrokeredBaseResponse)
      com.example.grpc.BrokeredBaseResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.BrokeredBaseResponse.class, com.example.grpc.BrokeredBaseResponse.Builder.class);
    }

    // Construct using com.example.grpc.BrokeredBaseResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBaseFieldBuilder();
        getResultStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      resultStatus_ = null;
      if (resultStatusBuilder_ != null) {
        resultStatusBuilder_.dispose();
        resultStatusBuilder_ = null;
      }
      locale_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredBaseResponse_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseResponse getDefaultInstanceForType() {
      return com.example.grpc.BrokeredBaseResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseResponse build() {
      com.example.grpc.BrokeredBaseResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredBaseResponse buildPartial() {
      com.example.grpc.BrokeredBaseResponse result = new com.example.grpc.BrokeredBaseResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.BrokeredBaseResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = baseBuilder_ == null
            ? base_
            : baseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resultStatus_ = resultStatusBuilder_ == null
            ? resultStatus_
            : resultStatusBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.locale_ = locale_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.BrokeredBaseResponse) {
        return mergeFrom((com.example.grpc.BrokeredBaseResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.BrokeredBaseResponse other) {
      if (other == com.example.grpc.BrokeredBaseResponse.getDefaultInstance()) return this;
      if (other.hasBase()) {
        mergeBase(other.getBase());
      }
      if (other.hasResultStatus()) {
        mergeResultStatus(other.getResultStatus());
      }
      if (!other.getLocale().isEmpty()) {
        locale_ = other.locale_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getResultStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              locale_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.example.grpc.BrokeredBaseMessage base_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder> baseBuilder_;
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     * @return Whether the base field is set.
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     * @return The base.
     */
    public com.example.grpc.BrokeredBaseMessage getBase() {
      if (baseBuilder_ == null) {
        return base_ == null ? com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
      } else {
        return baseBuilder_.getMessage();
      }
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder setBase(com.example.grpc.BrokeredBaseMessage value) {
      if (baseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        base_ = value;
      } else {
        baseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder setBase(
        com.example.grpc.BrokeredBaseMessage.Builder builderForValue) {
      if (baseBuilder_ == null) {
        base_ = builderForValue.build();
      } else {
        baseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder mergeBase(com.example.grpc.BrokeredBaseMessage value) {
      if (baseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          base_ != null &&
          base_ != com.example.grpc.BrokeredBaseMessage.getDefaultInstance()) {
          getBaseBuilder().mergeFrom(value);
        } else {
          base_ = value;
        }
      } else {
        baseBuilder_.mergeFrom(value);
      }
      if (base_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public Builder clearBase() {
      bitField0_ = (bitField0_ & ~0x00000001);
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public com.example.grpc.BrokeredBaseMessage.Builder getBaseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    public com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder() {
      if (baseBuilder_ != null) {
        return baseBuilder_.getMessageOrBuilder();
      } else {
        return base_ == null ?
            com.example.grpc.BrokeredBaseMessage.getDefaultInstance() : base_;
      }
    }
    /**
     * <code>.broker.BrokeredBaseMessage base = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder> 
        getBaseFieldBuilder() {
      if (baseBuilder_ == null) {
        baseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.grpc.BrokeredBaseMessage, com.example.grpc.BrokeredBaseMessage.Builder, com.example.grpc.BrokeredBaseMessageOrBuilder>(
                getBase(),
                getParentForChildren(),
                isClean());
        base_ = null;
      }
      return baseBuilder_;
    }

    private com.example.grpc.BrokeredResultStatus resultStatus_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredResultStatus, com.example.grpc.BrokeredResultStatus.Builder, com.example.grpc.BrokeredResultStatusOrBuilder> resultStatusBuilder_;
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     * @return Whether the resultStatus field is set.
     */
    public boolean hasResultStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     * @return The resultStatus.
     */
    public com.example.grpc.BrokeredResultStatus getResultStatus() {
      if (resultStatusBuilder_ == null) {
        return resultStatus_ == null ? com.example.grpc.BrokeredResultStatus.getDefaultInstance() : resultStatus_;
      } else {
        return resultStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public Builder setResultStatus(com.example.grpc.BrokeredResultStatus value) {
      if (resultStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resultStatus_ = value;
      } else {
        resultStatusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public Builder setResultStatus(
        com.example.grpc.BrokeredResultStatus.Builder builderForValue) {
      if (resultStatusBuilder_ == null) {
        resultStatus_ = builderForValue.build();
      } else {
        resultStatusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public Builder mergeResultStatus(com.example.grpc.BrokeredResultStatus value) {
      if (resultStatusBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          resultStatus_ != null &&
          resultStatus_ != com.example.grpc.BrokeredResultStatus.getDefaultInstance()) {
          getResultStatusBuilder().mergeFrom(value);
        } else {
          resultStatus_ = value;
        }
      } else {
        resultStatusBuilder_.mergeFrom(value);
      }
      if (resultStatus_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public Builder clearResultStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      resultStatus_ = null;
      if (resultStatusBuilder_ != null) {
        resultStatusBuilder_.dispose();
        resultStatusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public com.example.grpc.BrokeredResultStatus.Builder getResultStatusBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getResultStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    public com.example.grpc.BrokeredResultStatusOrBuilder getResultStatusOrBuilder() {
      if (resultStatusBuilder_ != null) {
        return resultStatusBuilder_.getMessageOrBuilder();
      } else {
        return resultStatus_ == null ?
            com.example.grpc.BrokeredResultStatus.getDefaultInstance() : resultStatus_;
      }
    }
    /**
     * <code>.broker.BrokeredResultStatus resultStatus = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.grpc.BrokeredResultStatus, com.example.grpc.BrokeredResultStatus.Builder, com.example.grpc.BrokeredResultStatusOrBuilder> 
        getResultStatusFieldBuilder() {
      if (resultStatusBuilder_ == null) {
        resultStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.grpc.BrokeredResultStatus, com.example.grpc.BrokeredResultStatus.Builder, com.example.grpc.BrokeredResultStatusOrBuilder>(
                getResultStatus(),
                getParentForChildren(),
                isClean());
        resultStatus_ = null;
      }
      return resultStatusBuilder_;
    }

    private java.lang.Object locale_ = "";
    /**
     * <code>string locale = 3;</code>
     * @return The locale.
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string locale = 3;</code>
     * @return The bytes for locale.
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string locale = 3;</code>
     * @param value The locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocale(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      locale_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string locale = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocale() {
      locale_ = getDefaultInstance().getLocale();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string locale = 3;</code>
     * @param value The bytes for locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      locale_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.BrokeredBaseResponse)
  }

  // @@protoc_insertion_point(class_scope:broker.BrokeredBaseResponse)
  private static final com.example.grpc.BrokeredBaseResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.BrokeredBaseResponse();
  }

  public static com.example.grpc.BrokeredBaseResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokeredBaseResponse>
      PARSER = new com.google.protobuf.AbstractParser<BrokeredBaseResponse>() {
    @java.lang.Override
    public BrokeredBaseResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BrokeredBaseResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokeredBaseResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.BrokeredBaseResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

