// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public final class BrokeredMessageProto {
  private BrokeredMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_BrokeredBaseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_BrokeredBaseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_BrokeredBaseCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_BrokeredBaseCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_BrokeredBaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_BrokeredBaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_BrokeredResultStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_BrokeredResultStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026brokered_message.proto\022\006broker\"`\n\023Brok" +
      "eredBaseMessage\022\025\n\rcorrelationId\030\001 \001(\t\022\020" +
      "\n\010tenantId\030\002 \001(\t\022\020\n\010tcUserId\030\003 \001(\t\022\016\n\006si" +
      "teId\030\004 \001(\t\"\304\001\n\023BrokeredBaseCommand\022)\n\004ba" +
      "se\030\001 \001(\0132\033.broker.BrokeredBaseMessage\022\023\n" +
      "\013tcSessionId\030\002 \001(\t\022\034\n\024eventHubPartitionI" +
      "ds\030\003 \001(\t\022\037\n\027currentContextSessionId\030\004 \001(" +
      "\t\022\036\n\026currentContextActionId\030\005 \001(\t\022\016\n\006loc" +
      "ale\030\006 \001(\t\"\205\001\n\024BrokeredBaseResponse\022)\n\004ba" +
      "se\030\001 \001(\0132\033.broker.BrokeredBaseMessage\0222\n" +
      "\014resultStatus\030\002 \001(\0132\034.broker.BrokeredRes" +
      "ultStatus\022\016\n\006locale\030\003 \001(\t\"V\n\024BrokeredRes" +
      "ultStatus\022\026\n\016httpStatusCode\030\001 \001(\005\022\022\n\nsta" +
      "tusText\030\002 \001(\t\022\022\n\nstackTrace\030\003 \001(\tB*\n\020com" +
      ".example.grpcB\024BrokeredMessageProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_broker_BrokeredBaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_broker_BrokeredBaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_BrokeredBaseMessage_descriptor,
        new java.lang.String[] { "CorrelationId", "TenantId", "TcUserId", "SiteId", });
    internal_static_broker_BrokeredBaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_broker_BrokeredBaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_BrokeredBaseCommand_descriptor,
        new java.lang.String[] { "Base", "TcSessionId", "EventHubPartitionIds", "CurrentContextSessionId", "CurrentContextActionId", "Locale", });
    internal_static_broker_BrokeredBaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_broker_BrokeredBaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_BrokeredBaseResponse_descriptor,
        new java.lang.String[] { "Base", "ResultStatus", "Locale", });
    internal_static_broker_BrokeredResultStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_broker_BrokeredResultStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_BrokeredResultStatus_descriptor,
        new java.lang.String[] { "HttpStatusCode", "StatusText", "StackTrace", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
