// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

/**
 * <pre>
 * Status model
 * </pre>
 *
 * Protobuf type {@code broker.BrokeredResultStatus}
 */
public final class BrokeredResultStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.BrokeredResultStatus)
    BrokeredResultStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokeredResultStatus.newBuilder() to construct.
  private BrokeredResultStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokeredResultStatus() {
    statusText_ = "";
    stackTrace_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokeredResultStatus();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredResultStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredResultStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.BrokeredResultStatus.class, com.example.grpc.BrokeredResultStatus.Builder.class);
  }

  public static final int HTTPSTATUSCODE_FIELD_NUMBER = 1;
  private int httpStatusCode_ = 0;
  /**
   * <code>int32 httpStatusCode = 1;</code>
   * @return The httpStatusCode.
   */
  @java.lang.Override
  public int getHttpStatusCode() {
    return httpStatusCode_;
  }

  public static final int STATUSTEXT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statusText_ = "";
  /**
   * <code>string statusText = 2;</code>
   * @return The statusText.
   */
  @java.lang.Override
  public java.lang.String getStatusText() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statusText_ = s;
      return s;
    }
  }
  /**
   * <code>string statusText = 2;</code>
   * @return The bytes for statusText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusTextBytes() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACKTRACE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stackTrace_ = "";
  /**
   * <code>string stackTrace = 3;</code>
   * @return The stackTrace.
   */
  @java.lang.Override
  public java.lang.String getStackTrace() {
    java.lang.Object ref = stackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stackTrace_ = s;
      return s;
    }
  }
  /**
   * <code>string stackTrace = 3;</code>
   * @return The bytes for stackTrace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStackTraceBytes() {
    java.lang.Object ref = stackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (httpStatusCode_ != 0) {
      output.writeInt32(1, httpStatusCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statusText_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stackTrace_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stackTrace_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (httpStatusCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, httpStatusCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statusText_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stackTrace_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stackTrace_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.BrokeredResultStatus)) {
      return super.equals(obj);
    }
    com.example.grpc.BrokeredResultStatus other = (com.example.grpc.BrokeredResultStatus) obj;

    if (getHttpStatusCode()
        != other.getHttpStatusCode()) return false;
    if (!getStatusText()
        .equals(other.getStatusText())) return false;
    if (!getStackTrace()
        .equals(other.getStackTrace())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HTTPSTATUSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getHttpStatusCode();
    hash = (37 * hash) + STATUSTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getStatusText().hashCode();
    hash = (37 * hash) + STACKTRACE_FIELD_NUMBER;
    hash = (53 * hash) + getStackTrace().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.BrokeredResultStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.BrokeredResultStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.BrokeredResultStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.BrokeredResultStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.BrokeredResultStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Status model
   * </pre>
   *
   * Protobuf type {@code broker.BrokeredResultStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.BrokeredResultStatus)
      com.example.grpc.BrokeredResultStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredResultStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredResultStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.BrokeredResultStatus.class, com.example.grpc.BrokeredResultStatus.Builder.class);
    }

    // Construct using com.example.grpc.BrokeredResultStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      httpStatusCode_ = 0;
      statusText_ = "";
      stackTrace_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_BrokeredResultStatus_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredResultStatus getDefaultInstanceForType() {
      return com.example.grpc.BrokeredResultStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.BrokeredResultStatus build() {
      com.example.grpc.BrokeredResultStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.BrokeredResultStatus buildPartial() {
      com.example.grpc.BrokeredResultStatus result = new com.example.grpc.BrokeredResultStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.BrokeredResultStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.httpStatusCode_ = httpStatusCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.statusText_ = statusText_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stackTrace_ = stackTrace_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.BrokeredResultStatus) {
        return mergeFrom((com.example.grpc.BrokeredResultStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.BrokeredResultStatus other) {
      if (other == com.example.grpc.BrokeredResultStatus.getDefaultInstance()) return this;
      if (other.getHttpStatusCode() != 0) {
        setHttpStatusCode(other.getHttpStatusCode());
      }
      if (!other.getStatusText().isEmpty()) {
        statusText_ = other.statusText_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getStackTrace().isEmpty()) {
        stackTrace_ = other.stackTrace_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              httpStatusCode_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              statusText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              stackTrace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int httpStatusCode_ ;
    /**
     * <code>int32 httpStatusCode = 1;</code>
     * @return The httpStatusCode.
     */
    @java.lang.Override
    public int getHttpStatusCode() {
      return httpStatusCode_;
    }
    /**
     * <code>int32 httpStatusCode = 1;</code>
     * @param value The httpStatusCode to set.
     * @return This builder for chaining.
     */
    public Builder setHttpStatusCode(int value) {

      httpStatusCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 httpStatusCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHttpStatusCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      httpStatusCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object statusText_ = "";
    /**
     * <code>string statusText = 2;</code>
     * @return The statusText.
     */
    public java.lang.String getStatusText() {
      java.lang.Object ref = statusText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string statusText = 2;</code>
     * @return The bytes for statusText.
     */
    public com.google.protobuf.ByteString
        getStatusTextBytes() {
      java.lang.Object ref = statusText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string statusText = 2;</code>
     * @param value The statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statusText_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string statusText = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusText() {
      statusText_ = getDefaultInstance().getStatusText();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string statusText = 2;</code>
     * @param value The bytes for statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      statusText_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object stackTrace_ = "";
    /**
     * <code>string stackTrace = 3;</code>
     * @return The stackTrace.
     */
    public java.lang.String getStackTrace() {
      java.lang.Object ref = stackTrace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stackTrace = 3;</code>
     * @return The bytes for stackTrace.
     */
    public com.google.protobuf.ByteString
        getStackTraceBytes() {
      java.lang.Object ref = stackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stackTrace = 3;</code>
     * @param value The stackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setStackTrace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stackTrace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string stackTrace = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStackTrace() {
      stackTrace_ = getDefaultInstance().getStackTrace();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string stackTrace = 3;</code>
     * @param value The bytes for stackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stackTrace_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.BrokeredResultStatus)
  }

  // @@protoc_insertion_point(class_scope:broker.BrokeredResultStatus)
  private static final com.example.grpc.BrokeredResultStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.BrokeredResultStatus();
  }

  public static com.example.grpc.BrokeredResultStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokeredResultStatus>
      PARSER = new com.google.protobuf.AbstractParser<BrokeredResultStatus>() {
    @java.lang.Override
    public BrokeredResultStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BrokeredResultStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokeredResultStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.BrokeredResultStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

