// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public final class BrokeredMessageProto {
  private BrokeredMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_TcBrokeredBaseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_TcBrokeredBaseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_TcBrokeredBaseCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_TcBrokeredBaseCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_TcBrokeredBaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_TcBrokeredBaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_TcBrokeredResultStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_TcBrokeredResultStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026brokered_message.proto\022\006broker\"b\n\025TcBr" +
      "okeredBaseMessage\022\025\n\rcorrelationId\030\001 \001(\t" +
      "\022\020\n\010tenantId\030\002 \001(\t\022\020\n\010tcUserId\030\003 \001(\t\022\016\n\006" +
      "siteId\030\004 \001(\t\"\310\001\n\025TcBrokeredBaseCommand\022+" +
      "\n\004base\030\001 \001(\0132\035.broker.TcBrokeredBaseMess" +
      "age\022\023\n\013tcSessionId\030\002 \001(\t\022\034\n\024eventHubPart" +
      "itionIds\030\003 \001(\t\022\037\n\027currentContextSessionI" +
      "d\030\004 \001(\t\022\036\n\026currentContextActionId\030\005 \001(\t\022" +
      "\016\n\006locale\030\006 \001(\t\"\213\001\n\026TcBrokeredBaseRespon" +
      "se\022+\n\004base\030\001 \001(\0132\035.broker.TcBrokeredBase" +
      "Message\0224\n\014resultStatus\030\002 \001(\0132\036.broker.T" +
      "cBrokeredResultStatus\022\016\n\006locale\030\003 \001(\t\"X\n" +
      "\026TcBrokeredResultStatus\022\026\n\016httpStatusCod" +
      "e\030\001 \001(\005\022\022\n\nstatusText\030\002 \001(\t\022\022\n\nstackTrac" +
      "e\030\003 \001(\tB*\n\020com.example.grpcB\024BrokeredMes" +
      "sageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_broker_TcBrokeredBaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_broker_TcBrokeredBaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_TcBrokeredBaseMessage_descriptor,
        new java.lang.String[] { "CorrelationId", "TenantId", "TcUserId", "SiteId", });
    internal_static_broker_TcBrokeredBaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_broker_TcBrokeredBaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_TcBrokeredBaseCommand_descriptor,
        new java.lang.String[] { "Base", "TcSessionId", "EventHubPartitionIds", "CurrentContextSessionId", "CurrentContextActionId", "Locale", });
    internal_static_broker_TcBrokeredBaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_broker_TcBrokeredBaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_TcBrokeredBaseResponse_descriptor,
        new java.lang.String[] { "Base", "ResultStatus", "Locale", });
    internal_static_broker_TcBrokeredResultStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_broker_TcBrokeredResultStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_TcBrokeredResultStatus_descriptor,
        new java.lang.String[] { "HttpStatusCode", "StatusText", "StackTrace", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
