// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface BrokeredBaseCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.BrokeredBaseCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   * @return The base.
   */
  com.example.grpc.BrokeredBaseMessage getBase();
  /**
   * <code>.broker.BrokeredBaseMessage base = 1;</code>
   */
  com.example.grpc.BrokeredBaseMessageOrBuilder getBaseOrBuilder();

  /**
   * <code>string tcSessionId = 2;</code>
   * @return The tcSessionId.
   */
  java.lang.String getTcSessionId();
  /**
   * <code>string tcSessionId = 2;</code>
   * @return The bytes for tcSessionId.
   */
  com.google.protobuf.ByteString
      getTcSessionIdBytes();

  /**
   * <code>string eventHubPartitionIds = 3;</code>
   * @return The eventHubPartitionIds.
   */
  java.lang.String getEventHubPartitionIds();
  /**
   * <code>string eventHubPartitionIds = 3;</code>
   * @return The bytes for eventHubPartitionIds.
   */
  com.google.protobuf.ByteString
      getEventHubPartitionIdsBytes();

  /**
   * <code>string currentContextSessionId = 4;</code>
   * @return The currentContextSessionId.
   */
  java.lang.String getCurrentContextSessionId();
  /**
   * <code>string currentContextSessionId = 4;</code>
   * @return The bytes for currentContextSessionId.
   */
  com.google.protobuf.ByteString
      getCurrentContextSessionIdBytes();

  /**
   * <code>string currentContextActionId = 5;</code>
   * @return The currentContextActionId.
   */
  java.lang.String getCurrentContextActionId();
  /**
   * <code>string currentContextActionId = 5;</code>
   * @return The bytes for currentContextActionId.
   */
  com.google.protobuf.ByteString
      getCurrentContextActionIdBytes();

  /**
   * <code>string locale = 6;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 6;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();
}
