// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_work_item_response.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface CreateWorkItemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.CreateWorkItemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.broker.TcBrokeredBaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.broker.TcBrokeredBaseResponse base = 1;</code>
   * @return The base.
   */
  com.example.grpc.TcBrokeredBaseResponse getBase();
  /**
   * <code>.broker.TcBrokeredBaseResponse base = 1;</code>
   */
  com.example.grpc.TcBrokeredBaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>string workItemId = 2;</code>
   * @return The workItemId.
   */
  java.lang.String getWorkItemId();
  /**
   * <code>string workItemId = 2;</code>
   * @return The bytes for workItemId.
   */
  com.google.protobuf.ByteString
      getWorkItemIdBytes();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
