// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_work_item_response.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public final class CreateWorkItemResponseProto {
  private CreateWorkItemResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_broker_CreateWorkItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_broker_CreateWorkItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037create_work_item_response.proto\022\006broke" +
      "r\032\026brokered_message.proto\"{\n\026CreateWorkI" +
      "temResponse\022,\n\004base\030\001 \001(\0132\036.broker.TcBro" +
      "keredBaseResponse\022\022\n\nworkItemId\030\002 \001(\t\022\016\n" +
      "\006status\030\003 \001(\t\022\017\n\007message\030\004 \001(\tB1\n\020com.ex" +
      "ample.grpcB\033CreateWorkItemResponseProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.grpc.BrokeredMessageProto.getDescriptor(),
        });
    internal_static_broker_CreateWorkItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_broker_CreateWorkItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_broker_CreateWorkItemResponse_descriptor,
        new java.lang.String[] { "Base", "WorkItemId", "Status", "Message", });
    com.example.grpc.BrokeredMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
