// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_work_item.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface CreateWorkItemCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.CreateWorkItemCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.broker.TcBrokeredBaseCommand base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.broker.TcBrokeredBaseCommand base = 1;</code>
   * @return The base.
   */
  com.example.grpc.TcBrokeredBaseCommand getBase();
  /**
   * <code>.broker.TcBrokeredBaseCommand base = 1;</code>
   */
  com.example.grpc.TcBrokeredBaseCommandOrBuilder getBaseOrBuilder();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string priority = 5;</code>
   * @return The priority.
   */
  java.lang.String getPriority();
  /**
   * <code>string priority = 5;</code>
   * @return The bytes for priority.
   */
  com.google.protobuf.ByteString
      getPriorityBytes();
}
