// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

/**
 * <pre>
 * Base message
 * </pre>
 *
 * Protobuf type {@code broker.TcBrokeredBaseMessage}
 */
public final class TcBrokeredBaseMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.TcBrokeredBaseMessage)
    TcBrokeredBaseMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TcBrokeredBaseMessage.newBuilder() to construct.
  private TcBrokeredBaseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TcBrokeredBaseMessage() {
    correlationId_ = "";
    tenantId_ = "";
    tcUserId_ = "";
    siteId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TcBrokeredBaseMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_TcBrokeredBaseMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.BrokeredMessageProto.internal_static_broker_TcBrokeredBaseMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.TcBrokeredBaseMessage.class, com.example.grpc.TcBrokeredBaseMessage.Builder.class);
  }

  public static final int CORRELATIONID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <code>string correlationId = 1;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <code>string correlationId = 1;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TCUSERID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tcUserId_ = "";
  /**
   * <code>string tcUserId = 3;</code>
   * @return The tcUserId.
   */
  @java.lang.Override
  public java.lang.String getTcUserId() {
    java.lang.Object ref = tcUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tcUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string tcUserId = 3;</code>
   * @return The bytes for tcUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTcUserIdBytes() {
    java.lang.Object ref = tcUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tcUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SITEID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object siteId_ = "";
  /**
   * <code>string siteId = 4;</code>
   * @return The siteId.
   */
  @java.lang.Override
  public java.lang.String getSiteId() {
    java.lang.Object ref = siteId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      siteId_ = s;
      return s;
    }
  }
  /**
   * <code>string siteId = 4;</code>
   * @return The bytes for siteId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSiteIdBytes() {
    java.lang.Object ref = siteId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      siteId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, correlationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcUserId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tcUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(siteId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, siteId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, correlationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tcUserId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tcUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(siteId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, siteId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.TcBrokeredBaseMessage)) {
      return super.equals(obj);
    }
    com.example.grpc.TcBrokeredBaseMessage other = (com.example.grpc.TcBrokeredBaseMessage) obj;

    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getTcUserId()
        .equals(other.getTcUserId())) return false;
    if (!getSiteId()
        .equals(other.getSiteId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + TCUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getTcUserId().hashCode();
    hash = (37 * hash) + SITEID_FIELD_NUMBER;
    hash = (53 * hash) + getSiteId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.TcBrokeredBaseMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.TcBrokeredBaseMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.TcBrokeredBaseMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.TcBrokeredBaseMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Base message
   * </pre>
   *
   * Protobuf type {@code broker.TcBrokeredBaseMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.TcBrokeredBaseMessage)
      com.example.grpc.TcBrokeredBaseMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_TcBrokeredBaseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_TcBrokeredBaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.TcBrokeredBaseMessage.class, com.example.grpc.TcBrokeredBaseMessage.Builder.class);
    }

    // Construct using com.example.grpc.TcBrokeredBaseMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      correlationId_ = "";
      tenantId_ = "";
      tcUserId_ = "";
      siteId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.BrokeredMessageProto.internal_static_broker_TcBrokeredBaseMessage_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.TcBrokeredBaseMessage getDefaultInstanceForType() {
      return com.example.grpc.TcBrokeredBaseMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.TcBrokeredBaseMessage build() {
      com.example.grpc.TcBrokeredBaseMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.TcBrokeredBaseMessage buildPartial() {
      com.example.grpc.TcBrokeredBaseMessage result = new com.example.grpc.TcBrokeredBaseMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.TcBrokeredBaseMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.correlationId_ = correlationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tcUserId_ = tcUserId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.siteId_ = siteId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.TcBrokeredBaseMessage) {
        return mergeFrom((com.example.grpc.TcBrokeredBaseMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.TcBrokeredBaseMessage other) {
      if (other == com.example.grpc.TcBrokeredBaseMessage.getDefaultInstance()) return this;
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTcUserId().isEmpty()) {
        tcUserId_ = other.tcUserId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSiteId().isEmpty()) {
        siteId_ = other.siteId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tcUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              siteId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object correlationId_ = "";
    /**
     * <code>string correlationId = 1;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string correlationId = 1;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string correlationId = 1;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 1;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenantId = 2;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenantId = 2;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenantId = 2;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tenantId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tenantId = 2;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tcUserId_ = "";
    /**
     * <code>string tcUserId = 3;</code>
     * @return The tcUserId.
     */
    public java.lang.String getTcUserId() {
      java.lang.Object ref = tcUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tcUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tcUserId = 3;</code>
     * @return The bytes for tcUserId.
     */
    public com.google.protobuf.ByteString
        getTcUserIdBytes() {
      java.lang.Object ref = tcUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tcUserId = 3;</code>
     * @param value The tcUserId to set.
     * @return This builder for chaining.
     */
    public Builder setTcUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tcUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tcUserId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTcUserId() {
      tcUserId_ = getDefaultInstance().getTcUserId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tcUserId = 3;</code>
     * @param value The bytes for tcUserId to set.
     * @return This builder for chaining.
     */
    public Builder setTcUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tcUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object siteId_ = "";
    /**
     * <code>string siteId = 4;</code>
     * @return The siteId.
     */
    public java.lang.String getSiteId() {
      java.lang.Object ref = siteId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string siteId = 4;</code>
     * @return The bytes for siteId.
     */
    public com.google.protobuf.ByteString
        getSiteIdBytes() {
      java.lang.Object ref = siteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string siteId = 4;</code>
     * @param value The siteId to set.
     * @return This builder for chaining.
     */
    public Builder setSiteId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      siteId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string siteId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSiteId() {
      siteId_ = getDefaultInstance().getSiteId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string siteId = 4;</code>
     * @param value The bytes for siteId to set.
     * @return This builder for chaining.
     */
    public Builder setSiteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      siteId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.TcBrokeredBaseMessage)
  }

  // @@protoc_insertion_point(class_scope:broker.TcBrokeredBaseMessage)
  private static final com.example.grpc.TcBrokeredBaseMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.TcBrokeredBaseMessage();
  }

  public static com.example.grpc.TcBrokeredBaseMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TcBrokeredBaseMessage>
      PARSER = new com.google.protobuf.AbstractParser<TcBrokeredBaseMessage>() {
    @java.lang.Override
    public TcBrokeredBaseMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TcBrokeredBaseMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TcBrokeredBaseMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.TcBrokeredBaseMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

