// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface TcBrokeredBaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.TcBrokeredBaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.broker.TcBrokeredBaseMessage base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.broker.TcBrokeredBaseMessage base = 1;</code>
   * @return The base.
   */
  com.example.grpc.TcBrokeredBaseMessage getBase();
  /**
   * <code>.broker.TcBrokeredBaseMessage base = 1;</code>
   */
  com.example.grpc.TcBrokeredBaseMessageOrBuilder getBaseOrBuilder();

  /**
   * <code>.broker.TcBrokeredResultStatus resultStatus = 2;</code>
   * @return Whether the resultStatus field is set.
   */
  boolean hasResultStatus();
  /**
   * <code>.broker.TcBrokeredResultStatus resultStatus = 2;</code>
   * @return The resultStatus.
   */
  com.example.grpc.TcBrokeredResultStatus getResultStatus();
  /**
   * <code>.broker.TcBrokeredResultStatus resultStatus = 2;</code>
   */
  com.example.grpc.TcBrokeredResultStatusOrBuilder getResultStatusOrBuilder();

  /**
   * <code>string locale = 3;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 3;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();
}
