// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokered_message.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface TcBrokeredResultStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.TcBrokeredResultStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 httpStatusCode = 1;</code>
   * @return The httpStatusCode.
   */
  int getHttpStatusCode();

  /**
   * <code>string statusText = 2;</code>
   * @return The statusText.
   */
  java.lang.String getStatusText();
  /**
   * <code>string statusText = 2;</code>
   * @return The bytes for statusText.
   */
  com.google.protobuf.ByteString
      getStatusTextBytes();

  /**
   * <code>string stackTrace = 3;</code>
   * @return The stackTrace.
   */
  java.lang.String getStackTrace();
  /**
   * <code>string stackTrace = 3;</code>
   * @return The bytes for stackTrace.
   */
  com.google.protobuf.ByteString
      getStackTraceBytes();
}
