// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSession.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public interface UserSessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserSession)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string userId = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string userUid = 3;</code>
   * @return The userUid.
   */
  java.lang.String getUserUid();
  /**
   * <code>string userUid = 3;</code>
   * @return The bytes for userUid.
   */
  com.google.protobuf.ByteString
      getUserUidBytes();
}
