// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSession.proto

// Protobuf Java Version: 3.25.1
package com.example.grpc;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserSession_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserSession_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserSession.proto\"A\n\013UserSession\022\021\n\tse" +
      "ssionId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\017\n\007userUid" +
      "\030\003 \001(\tB\037\n\020com.example.grpcB\tUserProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserSession_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserSession_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserSession_descriptor,
        new java.lang.String[] { "SessionId", "UserId", "UserUid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
